import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import '../styles/globals.css';
import React from "react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="fr">
          <head>
              <title>Web technologies m1</title>
          </head>
          <body>
          <Navbar/>
          <div className="m-10">
              {children}
          </div>
          <Footer/>
          </body>
      </html>
  )
}
